import os
import django

# Set up Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "store_manager.settings")
django.setup()

from dashboard.models import (
    Customer, Expense, Employee, Attendance, Supplier, PurchasedPhone,
    ElectronicService, Installment, DeliveryTracker, Treasury
)

models_list = [
    (Customer, 'customer', 'الزبائن'),
    (Expense, 'expense', 'المصاريف'),
    (Employee, 'employee', 'العمال'),
    (Attendance, 'attendance', 'الحضور والمغادرة'),
    (Supplier, 'supplier', 'الموردون'),
    (PurchasedPhone, 'purchased_phone', 'الهواتف المشتراة'),
    (ElectronicService, 'electronic_service', 'الخدمات الإلكترونية'),
    (Installment, 'installment', 'الأقساط'),
    (DeliveryTracker, 'delivery_tracker', 'تتبع الطلبيات'),
    (Treasury, 'treasury', 'الخزينة'),
]

views_code = "\n# --- AUTOGENERATED CRUD VIEWS ---\n"
views_code += "from django.urls import reverse\n"
views_code += "from .forms import *\n\n"

urls_code = "\n    # --- AUTOGENERATED CRUD URLS ---\n"

templates_dir = os.path.join('templates', 'dashboard')

for model, name, title in models_list:
    model_name = model.__name__
    form_name = f"{model_name}Form"
    
    # Generate Views
    views_code += f"""
@login_required
def {name}_list(request):
    items = {model_name}.objects.all()
    return render(request, 'dashboard/{name}_list.html', {{'items': items}})

@login_required
def add_{name}(request):
    if request.method == 'POST':
        form = {form_name}(request.POST)
        if form.is_valid():
            form.save()
            return redirect('{name}_list')
    else:
        form = {form_name}()
    return render(request, 'dashboard/generic_form.html', {{
        'form': form, 
        'title': 'إضافة {title}',
        'cancel_url': reverse('{name}_list')
    }})

@login_required
def edit_{name}(request, pk):
    item = get_object_or_404({model_name}, pk=pk)
    if request.method == 'POST':
        form = {form_name}(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('{name}_list')
    else:
        form = {form_name}(instance=item)
    return render(request, 'dashboard/generic_form.html', {{
        'form': form, 
        'title': 'تعديل {title}',
        'cancel_url': reverse('{name}_list')
    }})
"""
    
    # Generate URLs
    urls_code += f"    path('{name.replace('_', '-')}/', views.{name}_list, name='{name}_list'),\n"
    urls_code += f"    path('{name.replace('_', '-')}/add/', views.add_{name}, name='add_{name}'),\n"
    urls_code += f"    path('{name.replace('_', '-')}/edit/<int:pk>/', views.edit_{name}, name='edit_{name}'),\n"

    # Generate Templates
    fields = [f for f in model._meta.fields if f.name != 'id']
    headers = "".join([f"            <th style='padding: 10px; border: 1px solid #e0e0e0;'>{f.verbose_name or f.name}</th>\n" for f in fields])
    cells = ""
    for f in fields:
        if f.choices:
            cells += f"            <td style='padding: 10px; border: 1px solid #e0e0e0;'>{{{{ item.get_{f.name}_display }}}}</td>\n"
        else:
            cells += f"            <td style='padding: 10px; border: 1px solid #e0e0e0;'>{{{{ item.{f.name} }}}}</td>\n"

    template_code = f"""{{% extends 'base.html' %}}

{{% block content %}}
<div dir="rtl" style="padding: 20px;">
    <h2>📋 {title}</h2>
    <a href="{{% url 'add_{name}' %}}" style="background: #3a7bc8; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; display: inline-block; margin-bottom: 20px; font-weight: bold;">➕ إضافة عنصر جديد</a>
    
    <div style="overflow-x: auto;">
        <table style="width: 100%; border-collapse: collapse; text-align: center; background: white; border: 1px solid #e0e0e0; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
            <tr style="background: #f7f9fc; color: #1e3a5f;">
{headers}            <th style="padding: 10px; border: 1px solid #e0e0e0;">إجراءات</th>
            </tr>
            {{% for item in items %}}
            <tr style="transition: background 0.2s;" onmouseover="this.style.background='#f1f5f9';" onmouseout="this.style.background='white';">
{cells}            <td style="padding: 10px; border: 1px solid #e0e0e0;">
                    <a href="{{% url 'edit_{name}' item.id %}}" style="color: #f39c12; text-decoration: none; font-weight: bold;">تعديل ✏️</a>
                </td>
            </tr>
            {{% empty %}}
            <tr>
                <td colspan="{len(fields) + 1}" style="padding: 20px; color: #7f8c8d;">لا توجد بيانات حالياً.</td>
            </tr>
            {{% endfor %}}
        </table>
    </div>
</div>
{{% endblock %}}
"""
    with open(os.path.join(templates_dir, f"{name}_list.html"), "w", encoding="utf-8") as f:
        f.write(template_code)

# Append to views.py
with open("dashboard/views.py", "a", encoding="utf-8") as f:
    f.write(views_code)

# Inject into urls.py
with open("dashboard/urls.py", "r", encoding="utf-8") as f:
    urls_content = f.read()

urls_content = urls_content.replace("]", urls_code + "]")

with open("dashboard/urls.py", "w", encoding="utf-8") as f:
    f.write(urls_content)

print("SUCCESS")
