# Generated by Django 5.0.4 on 2026-05-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الزبون')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ديون الزبون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.CharField(max_length=250, verbose_name='تفاصيل الطلبية')),
                ('delivery_person', models.CharField(max_length=100, verbose_name='عامل التوصيل')),
                ('status', models.BooleanField(default=False, verbose_name='تم التوصيل؟')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='اسم الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم العامل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المصروف')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='اسم الزبون')),
                ('device_info', models.CharField(max_length=200, verbose_name='نوع الجهاز والمشكلة')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الصيانة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد الصيانة'), ('completed', 'مكتملة'), ('external', 'صيانة خارجية')], default='pending', max_length=20, verbose_name='حالة الصيانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ديون المورد')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('is_present', models.BooleanField(default=True, verbose_name='حاضر؟')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee', verbose_name='العامل')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('due_date', models.DateField(verbose_name='تاريخ القسط القادم')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer', verbose_name='الزبون')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='نوع الهاتف')),
                ('imei', models.CharField(max_length=50, unique=True, verbose_name='رقم التسلسل (IMEI)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('date_purchased', models.DateField(auto_now_add=True, verbose_name='تاريخ الشراء')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.supplier', verbose_name='المورد')),
            ],
        ),
    ]
