# Generated by Django 5.0.4 on 2026-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1500.0, max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=25000.0, max_digits=10, null=True, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, max_digits=10, null=True, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000.0, max_digits=10, null=True, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=40000.0, max_digits=10, null=True, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000.0, max_digits=10, null=True, verbose_name='المبلغ الإجمالي'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True, verbose_name='تكلفة الصيانة'),
        ),
        migrations.AlterField(
            model_name='purchasedphone',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=15000.0, max_digits=10, null=True, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchasedphone',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20000.0, max_digits=10, null=True, verbose_name='سعر البيع'),
        ),
    ]
