# Generated by Django 5.0.4 on 2026-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_electronicservice_price_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracker',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر التوصيل'),
        ),
    ]
