# Generated by Django 5.0.4 on 2026-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_deliverytracker_delivery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رأس المال الافتتاحي')),
            ],
            options={
                'verbose_name': 'الخزينة',
                'verbose_name_plural': 'الخزينة',
            },
        ),
        migrations.AddField(
            model_name='purchasedphone',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='تم البيع؟'),
        ),
    ]
