# Generated by Django 5.0.4 on 2026-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_treasury_purchasedphone_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع المنتجات المشتراة'),
        ),
    ]
