# Generated by Django 5.0.4 on 2026-06-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_supplier_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedphone',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الهواتف'),
        ),
    ]
